version: "3.8"

services:
  backend:
    build:
      context: ../../
      dockerfile: infra/docker/Dockerfile.backend
    container_name: healthcare-backend
    ports:
      - "5000:5000"
    volumes:
      - ../../backend:/app/backend
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:6543/healthcare
      - OPENAI_API_KEY=${OPENAI_API_KEY}  # Make sure to set in .env or export in shell
    depends_on:
      - postgres
    restart: unless-stopped

  patient-frontend:
    build:
      context: ../../frontend/patient-app
      dockerfile: ../../infra/docker/Dockerfile.patient
    container_name: patient-frontend
    ports:
      - "3000:3000"
    volumes:
      - ../../frontend/patient-app:/app
    restart: unless-stopped

  postgres:
    image: postgres:14
    container_name: healthcare-postgres
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=healthcare
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:

